name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: node:alpine3.19
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build
    - run: npm test
